2024-02-23 03:09:28,960 - easytorch-training - INFO - Initializing training.
2024-02-23 03:09:28,960 - easytorch-training - INFO - Set clip grad, param: {'max_norm': 5.0}
2024-02-23 03:09:28,960 - easytorch-training - INFO - Building training data loader.
2024-02-23 03:09:29,001 - easytorch-training - INFO - Set optim: Adam (
Parameter Group 0
    amsgrad: False
    betas: [0.9, 0.95]
    eps: 1e-08
    lr: 0.001
    weight_decay: 0
)
2024-02-23 03:09:29,001 - easytorch-training - INFO - Set lr_scheduler: <torch.optim.lr_scheduler.MultiStepLR object at 0x7f999b5189d0>
2024-02-23 03:09:29,002 - easytorch-training - INFO - Initializing validation.
2024-02-23 03:09:29,002 - easytorch-training - INFO - Building val data loader.
2024-02-23 03:09:29,086 - easytorch-training - INFO - Epoch 1 / 200
2024-02-23 03:10:17,368 - easytorch-training - ERROR - Traceback (most recent call last):
  File "/root/py_time_forecasting/STEP/basicts/launcher.py", line 20, in launch_training
    easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)
TypeError: launch_training() got an unexpected keyword argument 'devices'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/step/lib/python3.9/site-packages/easytorch/launcher/launcher.py", line 52, in training_func
    runner.train(cfg)
  File "/root/anaconda3/envs/step/lib/python3.9/site-packages/easytorch/core/runner.py", line 351, in train
    loss = self.train_iters(epoch, iter_index, data)
  File "/root/py_time_forecasting/STEP/basicts/runners/base_tsf_runner.py", line 238, in train_iters
    forward_return = list(self.forward(data=data, epoch=epoch, iter_num=iter_num, train=True))
  File "/root/py_time_forecasting/STEP/step/step_runner/tsformer_runner.py", line 65, in forward
    reconstruction_masked_tokens, label_masked_tokens = self.model(history_data=history_data, future_data=None, batch_seen=iter_num, epoch=epoch)
  File "/root/anaconda3/envs/step/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/py_time_forecasting/STEP/step/step_arch/tsformer/tsformer.py", line 187, in forward
    reconstruction_masked_tokens, label_masked_tokens = self.get_reconstructed_masked_tokens(reconstruction_full, history_data, unmasked_token_index, masked_token_index)
  File "/root/py_time_forecasting/STEP/step/step_arch/tsformer/tsformer.py", line 157, in get_reconstructed_masked_tokens
    label_masked_tokens = label_full[:, :, masked_token_index, :].contiguous() # B, N, r*P, d
KeyboardInterrupt

